# Generated by Django 3.2 on 2023-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20231006_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
